/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xdbc_XClient */

#ifndef _Included_xdbc_XClient
#define _Included_xdbc_XClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      xdbc_XClient
 * Method:     initialize
 * Signature:  (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_xdbc_XClient_initialize
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:      xdbc_XClient
 * Method:     startReceiving0
 * Signature:  (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_xdbc_XClient_startReceiving0
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:      xdbc_XClient
 * Method:     hasNext0
 * Signature:  (J)I
 */
JNIEXPORT jint JNICALL Java_xdbc_XClient_hasNext0
  (JNIEnv *, jobject, jlong);

/*
 * Class:      xdbc_XClient
 * Method:     getBuffer0
 * Signature:  (JLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_xdbc_XClient_getBuffer0
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:      xdbc_XClient
 * Method:     markBufferAsRead0
 * Signature:  (JI)I
 */
JNIEXPORT jint JNICALL Java_xdbc_XClient_markBufferAsRead0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:      xdbc_XClient
 * Method:     finalize0
 * Signature:  (J)I
 */
JNIEXPORT jint JNICALL Java_xdbc_XClient_finalize0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
