package example

import scala.io.Source
import org.apache.spark.sql.types._

object SchemataOld {

  def readFileAsString(filePath: String): String = {
    val fileSource = Source.fromFile(filePath)

    // Read the entire file content and concatenate it into a single string
    val fileContent = fileSource.getLines().mkString("\n")

    // Close the file to free up resources
    fileSource.close()

    // Return the file content as a string
    fileContent
  }

  println(readFileAsString("/xdbc-client/tests/schemas/lineitem_sf10.json"))

  val schemaTupleSizeMap: Map[String, Integer] = Map(
    "lineitem_sf10" -> 165,
    "inputeventsm" -> 0,
    "ss13husallm" -> 0,
    "iotm" -> 0
  )

  val schemaRowsMap: Map[String, Long] = Map(
    "lineitem_sf10" -> 59986052L,
    "inputeventsm" -> 8978893,
    "ss13husallm" -> 1476313,
    "iotm" -> 5833099L
  )

  val lineitemSchema = StructType(Seq(
    StructField("l_orderkey", IntegerType),
    StructField("l_partkey", IntegerType),
    StructField("l_suppkey", IntegerType),
    StructField("l_linenumber", IntegerType),
    StructField("l_quantity", DoubleType),
    StructField("l_extendedprice", DoubleType),
    StructField("l_discount", DoubleType),
    StructField("l_tax", DoubleType),
    StructField("l_returnflag", StringType),
    StructField("l_linestatus", StringType),
    StructField("l_shipdate", StringType),
    StructField("l_commitdate", StringType),
    StructField("l_receiptdate", StringType),
    StructField("l_shipinstruct", StringType),
    StructField("l_shipmode", StringType),
    StructField("l_comment", StringType)
  ))

  val inputeventsmSchema = StructType(Seq(
    StructField("subject_id", IntegerType),
    StructField("hadm_id", IntegerType),
    StructField("stay_id", IntegerType),
    StructField("caregiver_id", IntegerType),
    StructField("starttime", StringType),
    StructField("endtime", StringType),
    StructField("storetime", StringType),
    StructField("itemid", IntegerType),
    StructField("amount", DoubleType),
    StructField("amountuom", StringType),
    StructField("rate", DoubleType),
    StructField("rateuom", StringType),
    StructField("orderid", IntegerType),
    StructField("linkorderid", IntegerType),
    StructField("ordercategoryname", StringType),
    StructField("secondaryordercategoryname", StringType),
    StructField("ordercomponenttypedescription", StringType),
    StructField("ordercategorydescription", StringType),
    StructField("patientweight", DoubleType),
    StructField("totalamount", DoubleType),
    StructField("totalamountuom", StringType),
    StructField("isopenbag", IntegerType),
    StructField("continueinnextdept", IntegerType),
    StructField("statusdescription", StringType),
    StructField("originalamount", DoubleType),
    StructField("originalrate", DoubleType)
  ))

  val ss13husallmSchema = StructType(Seq(
    StructField("SERIALNO", IntegerType),
    StructField("DIVISION", IntegerType),
    StructField("PUMA", IntegerType),
    StructField("REGION", IntegerType),
    StructField("ST", IntegerType),
    StructField("ADJHSG", IntegerType),
    StructField("ADJINC", IntegerType),
    StructField("WGTP", IntegerType),
    StructField("NP", IntegerType),
    StructField("TYPE", IntegerType),
    StructField("ACCESS", IntegerType),
    StructField("ACR", IntegerType),
    StructField("AGS", IntegerType),
    StructField("BATH", IntegerType),
    StructField("BDSP", IntegerType),
    StructField("BLD", IntegerType),
    StructField("BROADBND", IntegerType),
    StructField("BUS", IntegerType),
    StructField("COMPOTHX", IntegerType),
    StructField("CONP", IntegerType),
    StructField("DIALUP", IntegerType),
    StructField("DSL", IntegerType),
    StructField("ELEP", IntegerType),
    StructField("FIBEROP", IntegerType),
    StructField("FS", IntegerType),
    StructField("FULP", IntegerType),
    StructField("GASP", IntegerType),
    StructField("HANDHELD", IntegerType),
    StructField("HFL", IntegerType),
    StructField("INSP", IntegerType),
    StructField("LAPTOP", IntegerType),
    StructField("MHP", IntegerType),
    StructField("MODEM", IntegerType),
    StructField("MRGI", IntegerType),
    StructField("MRGP", IntegerType),
    StructField("MRGT", IntegerType),
    StructField("MRGX", IntegerType),
    StructField("OTHSVCEX", IntegerType),
    StructField("REFR", IntegerType),
    StructField("RMSP", IntegerType),
    StructField("RNTM", IntegerType),
    StructField("RNTP", IntegerType),
    StructField("RWAT", IntegerType),
    StructField("RWATPR", IntegerType),
    StructField("SATELLITE", IntegerType),
    StructField("SINK", IntegerType),
    StructField("SMP", IntegerType),
    StructField("STOV", IntegerType),
    StructField("TEL", IntegerType),
    StructField("TEN", IntegerType),
    StructField("TOIL", IntegerType),
    StructField("VACS", IntegerType),
    StructField("VALP", IntegerType),
    StructField("VEH", IntegerType),
    StructField("WATP", IntegerType),
    StructField("YBL", IntegerType),
    StructField("FES", IntegerType),
    StructField("FFINCP", IntegerType),
    StructField("FGRNTP", IntegerType),
    StructField("FHINCP", IntegerType),
    StructField("FINCP", IntegerType),
    StructField("FPARC", IntegerType),
    StructField("FSMOCP", IntegerType),
    StructField("GRNTP", IntegerType),
    StructField("GRPIP", IntegerType),
    StructField("HHL", IntegerType),
    StructField("HHT", IntegerType),
    StructField("HINCP", IntegerType),
    StructField("HUGCL", IntegerType),
    StructField("HUPAC", IntegerType),
    StructField("HUPAOC", IntegerType),
    StructField("HUPARC", IntegerType),
    StructField("KIT", IntegerType),
    StructField("LNGI", IntegerType),
    StructField("MULTG", IntegerType),
    StructField("MV", IntegerType),
    StructField("NOC", IntegerType),
    StructField("NPF", IntegerType),
    StructField("NPP", IntegerType),
    StructField("NR", IntegerType),
    StructField("NRC", IntegerType),
    StructField("OCPIP", IntegerType),
    StructField("PARTNER", IntegerType),
    StructField("PLM", IntegerType),
    StructField("PSF", IntegerType),
    StructField("R18", IntegerType),
    StructField("R60", IntegerType),
    StructField("R65", IntegerType),
    StructField("RESMODE", IntegerType),
    StructField("SMOCP", IntegerType),
    StructField("SMX", IntegerType),
    StructField("SRNT", IntegerType),
    StructField("SSMC", IntegerType),
    StructField("SVAL", IntegerType),
    StructField("TAXP", IntegerType),
    StructField("WIF", IntegerType),
    StructField("WKEXREL", IntegerType),
    StructField("WORKSTAT", IntegerType),
    StructField("FACCESSP", IntegerType),
    StructField("FACRP", IntegerType),
    StructField("FAGSP", IntegerType),
    StructField("FBATHP", IntegerType),
    StructField("FBDSP", IntegerType),
    StructField("FBLDP", IntegerType),
    StructField("FBROADBNDP", IntegerType),
    StructField("FBUSP", IntegerType),
    StructField("FCOMPOTHXP", IntegerType),
    StructField("FCONP", IntegerType),
    StructField("FDIALUPP", IntegerType),
    StructField("FDSLP", IntegerType),
    StructField("FELEP", IntegerType),
    StructField("FFIBEROPP", IntegerType),
    StructField("FFSP", IntegerType),
    StructField("FFULP", IntegerType),
    StructField("FGASP", IntegerType),
    StructField("FHANDHELDP", IntegerType),
    StructField("FHFLP", IntegerType),
    StructField("FINSP", IntegerType),
    StructField("FKITP", IntegerType),
    StructField("FLAPTOPP", IntegerType),
    StructField("FMHP", IntegerType),
    StructField("FMODEMP", IntegerType),
    StructField("FMRGIP", IntegerType),
    StructField("FMRGP", IntegerType),
    StructField("FMRGTP", IntegerType),
    StructField("FMRGXP", IntegerType),
    StructField("FMVP", IntegerType),
    StructField("FOTHSVCEXP", IntegerType),
    StructField("FPLMP", IntegerType),
    StructField("FREFRP", IntegerType),
    StructField("FRMSP", IntegerType),
    StructField("FRNTMP", IntegerType),
    StructField("FRNTP", IntegerType),
    StructField("FRWATP", IntegerType),
    StructField("FRWATPRP", IntegerType),
    StructField("FSATELLITEP", IntegerType),
    StructField("FSINKP", IntegerType),
    StructField("FSMP", IntegerType),
    StructField("FSMXHP", IntegerType),
    StructField("FSMXSP", IntegerType),
    StructField("FSTOVP", IntegerType),
    StructField("FTAXP", IntegerType),
    StructField("FTELP", IntegerType),
    StructField("FTENP", IntegerType),
    StructField("FTOILP", IntegerType),
    StructField("FVACSP", IntegerType),
    StructField("FVALP", IntegerType),
    StructField("FVEHP", IntegerType),
    StructField("FWATP", IntegerType),
    StructField("FYBLP", IntegerType),
    StructField("wgtp1", IntegerType),
    StructField("wgtp2", IntegerType),
    StructField("wgtp3", IntegerType),
    StructField("wgtp4", IntegerType),
    StructField("wgtp5", IntegerType),
    StructField("wgtp6", IntegerType),
    StructField("wgtp7", IntegerType),
    StructField("wgtp8", IntegerType),
    StructField("wgtp9", IntegerType),
    StructField("wgtp10", IntegerType),
    StructField("wgtp11", IntegerType),
    StructField("wgtp12", IntegerType),
    StructField("wgtp13", IntegerType),
    StructField("wgtp14", IntegerType),
    StructField("wgtp15", IntegerType),
    StructField("wgtp16", IntegerType),
    StructField("wgtp17", IntegerType),
    StructField("wgtp18", IntegerType),
    StructField("wgtp19", IntegerType),
    StructField("wgtp20", IntegerType),
    StructField("wgtp21", IntegerType),
    StructField("wgtp22", IntegerType),
    StructField("wgtp23", IntegerType),
    StructField("wgtp24", IntegerType),
    StructField("wgtp25", IntegerType),
    StructField("wgtp26", IntegerType),
    StructField("wgtp27", IntegerType),
    StructField("wgtp28", IntegerType),
    StructField("wgtp29", IntegerType),
    StructField("wgtp30", IntegerType),
    StructField("wgtp31", IntegerType),
    StructField("wgtp32", IntegerType),
    StructField("wgtp33", IntegerType),
    StructField("wgtp34", IntegerType),
    StructField("wgtp35", IntegerType),
    StructField("wgtp36", IntegerType),
    StructField("wgtp37", IntegerType),
    StructField("wgtp38", IntegerType),
    StructField("wgtp39", IntegerType),
    StructField("wgtp40", IntegerType),
    StructField("wgtp41", IntegerType),
    StructField("wgtp42", IntegerType),
    StructField("wgtp43", IntegerType),
    StructField("wgtp44", IntegerType),
    StructField("wgtp45", IntegerType),
    StructField("wgtp46", IntegerType),
    StructField("wgtp47", IntegerType),
    StructField("wgtp48", IntegerType),
    StructField("wgtp49", IntegerType),
    StructField("wgtp50", IntegerType),
    StructField("wgtp51", IntegerType),
    StructField("wgtp52", IntegerType),
    StructField("wgtp53", IntegerType),
    StructField("wgtp54", IntegerType),
    StructField("wgtp55", IntegerType),
    StructField("wgtp56", IntegerType),
    StructField("wgtp57", IntegerType),
    StructField("wgtp58", IntegerType),
    StructField("wgtp59", IntegerType),
    StructField("wgtp60", IntegerType),
    StructField("wgtp61", IntegerType),
    StructField("wgtp62", IntegerType),
    StructField("wgtp63", IntegerType),
    StructField("wgtp64", IntegerType),
    StructField("wgtp65", IntegerType),
    StructField("wgtp66", IntegerType),
    StructField("wgtp67", IntegerType),
    StructField("wgtp68", IntegerType),
    StructField("wgtp69", IntegerType),
    StructField("wgtp70", IntegerType),
    StructField("wgtp71", IntegerType),
    StructField("wgtp72", IntegerType),
    StructField("wgtp73", IntegerType),
    StructField("wgtp74", IntegerType),
    StructField("wgtp75", IntegerType),
    StructField("wgtp76", IntegerType),
    StructField("wgtp77", IntegerType),
    StructField("wgtp78", IntegerType),
    StructField("wgtp79", IntegerType),
    StructField("wgtp80", IntegerType)
  ))


  val iotmSchema = StructType(Seq(
    StructField("id", IntegerType),
    StructField("FlowID", StringType),
    StructField("SrcIP", StringType),
    StructField("SrcPort", IntegerType),
    StructField("DstIP", StringType),
    StructField("DstPort", IntegerType),
    StructField("Protocol", IntegerType),
    StructField("Timestamp", StringType),
    StructField("FlowDuration", IntegerType),
    StructField("TotFwdPkts", IntegerType),
    StructField("TotBwdPkts", IntegerType),
    StructField("TotLenFwdPkts", DoubleType),
    StructField("TotLenBwdPkts", DoubleType),
    StructField("FwdPktLenMax", DoubleType),
    StructField("FwdPktLenMin", DoubleType),
    StructField("FwdPktLenMean", DoubleType),
    StructField("FwdPktLenStd", DoubleType),
    StructField("BwdPktLenMax", DoubleType),
    StructField("BwdPktLenMin", DoubleType),
    StructField("BwdPktLenMean", DoubleType),
    StructField("BwdPktLenStd", DoubleType),
    StructField("FlowBytsPerS", DoubleType),
    StructField("FlowPktsPerS", DoubleType),
    StructField("FlowIATMean", DoubleType),
    StructField("FlowIATStd", DoubleType),
    StructField("FlowIATMax", DoubleType),
    StructField("FlowIATMin", DoubleType),
    StructField("FwdIATTot", DoubleType),
    StructField("FwdIATMean", DoubleType),
    StructField("FwdIATStd", DoubleType),
    StructField("FwdIATMax", DoubleType),
    StructField("FwdIATMin", DoubleType),
    StructField("BwdIATTot", DoubleType),
    StructField("BwdIATMean", DoubleType),
    StructField("BwdIATStd", DoubleType),
    StructField("BwdIATMax", DoubleType),
    StructField("BwdIATMin", DoubleType),
    StructField("FwdPSHFlags", IntegerType),
    StructField("BwdPSHFlags", IntegerType),
    StructField("FwdURGFlags", IntegerType),
    StructField("BwdURGFlags", IntegerType),
    StructField("FwdHeaderLen", IntegerType),
    StructField("BwdHeaderLen", IntegerType),
    StructField("FwdPktsPerS", DoubleType),
    StructField("BwdPktsPerS", DoubleType),
    StructField("PktLenMin", DoubleType),
    StructField("PktLenMax", DoubleType),
    StructField("PktLenMean", DoubleType),
    StructField("PktLenStd", DoubleType),
    StructField("PktLenVar", DoubleType),
    StructField("FINFlagCnt", IntegerType),
    StructField("SYNFlagCnt", IntegerType),
    StructField("RSTFlagCnt", IntegerType),
    StructField("PSHFlagCnt", IntegerType),
    StructField("ACKFlagCnt", IntegerType),
    StructField("URGFlagCnt", IntegerType),
    StructField("CWEFlagCount", IntegerType),
    StructField("ECEFlagCnt", IntegerType),
    StructField("DownPerUpRatio", DoubleType),
    StructField("PktSizeAvg", DoubleType),
    StructField("FwdSegSizeAvg", DoubleType),
    StructField("BwdSegSizeAvg", DoubleType),
    StructField("FwdBytsPerbAvg", IntegerType),
    StructField("FwdPktsPerbAvg", IntegerType),
    StructField("FwdBlkRateAvg", IntegerType),
    StructField("BwdBytsPerbAvg", IntegerType),
    StructField("BwdPktsPerbAvg", IntegerType),
    StructField("BwdBlkRateAvg", IntegerType),
    StructField("SubflowFwdPkts", IntegerType),
    StructField("SubflowFwdByts", IntegerType),
    StructField("SubflowBwdPkts", IntegerType),
    StructField("SubflowBwdByts", IntegerType),
    StructField("InitFwdWinByts", IntegerType),
    StructField("InitBwdWinByts", IntegerType),
    StructField("FwdActDataPkts", IntegerType),
    StructField("FwdSegSizeMin", IntegerType),
    StructField("ActiveMean", IntegerType),
    StructField("ActiveStd", IntegerType),
    StructField("ActiveMax", IntegerType),
    StructField("ActiveMin", IntegerType),
    StructField("IdleMean", DoubleType),
    StructField("IdleStd", DoubleType),
    StructField("IdleMax", DoubleType),
    StructField("IdleMin", DoubleType),
    StructField("Label", StringType)
  ))


  val schemaMap: Map[String, StructType] = Map(
    "lineitem_sf10" -> lineitemSchema,
    "inputeventsm" -> inputeventsmSchema,
    "ss13husallm" -> ss13husallmSchema,
    "iotm" -> iotmSchema
  )
}
